version: '3.5'
services:
  mysql:
    image: "mysql:8.0"
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    cap_add:
      - SYS_NICE  # silently mbind: Operation not permitted
    environment:
      - MYSQL_ROOT_PASSWORD=root # password
      - TZ=Asia/Taipei
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    name: ${NETWORKS:-internal}
    driver: bridge