version: '3.5'

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=jira,bitbucket,confluence
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d # 預先建立databases
    networks:
      - internal
networks:
  internal:
    name: internal
    driver: bridge